device: cuda:1
random_seed: 0
log:
  dir: ../../log/inverse_problem
inverse:
  IAEA:
    use: true
    input_path:  ../../data/processed/IAEA/interpolation_voronoi_vib_0_noise_0.0_[0, 10, 20, 30, 40, 50, 60, 70, 80, 85]_[0, 10, 20, 30, 40, 50, 60, 70, 80, 85].npy
    predict_path: ../../data/processed/IAEA/phione.npy
    train_ratio: 0.85
    val_ratio: 0.05
    batch_size: 64
    criterion:
      type: mse
    model:
      overwrite: true # if overwrite the previous pth
      type: NVT-ResNet
      path: ../../data/model_weights/IAEA/{output}/{type}_{input}.pth
    train:
      use: true
      lr: 0.005
      epochs: 100
      optimizer:
        type: adam
        args:
          weight_decay: 0.0001
      scheduler:
        type: step_lr
        args:
          gamma: 0.05
          step_size: 50
    test:
      use: true

  NOAA:
    use: false
    input_path: ../../data/processed/NOAA/obs_float64_1_mean_vib_0_noise_0.0_[0, 20, 40, 60, 80, 100, 120, 140, 160]_[0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340].npy
    predict_path: ../../data/processed/NOAA/NOAA_float64_1_mean.npy
    train_ratio: 0.85
    val_ratio: 0.05
    batch_size: 64
    criterion:
      type: mse
    model:
      overwrite: true # if overwrite the previous pth
      type: EIM-NN
      path: ../../data/model_weights/NOAA/{output}/{type}_{input}.pth
      args:
        basis_path: ../../data/extract_basis/NOAA/SVD_base_number_10.npz
        x_shape: 180
        y_shape: 360
    train:
      use: true
      lr: 0.1
      epochs: 100
      optimizer:
        type: adam
        args:
          weight_decay: 0.0001
      scheduler:
        type: step_lr
        args:
          gamma: 0.05
          step_size: 50
    test:
      use: true




